force-app/main/default/objects/CampaignMemberStatus__c/CampaignMemberStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Defines Campaign Member Status values to create automatically.</description>
    <label>AAuto Kampaign Member Status</label>
</CustomObject>

force-app/main/default/objects/CampaignMemberStatus__c/fields/Campaign_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Member_Status__c</fullName>
    <description>The label of the status to automatically apply to new campaigns.</description>
    <inlineHelpText>The label of the status to automatically apply to new campaigns.</inlineHelpText>
    <label>Campaign Member Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMemberStatus__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>Which campaign types should get these statuses?</description>
    <inlineHelpText>Which campaign types should get these statuses?</inlineHelpText>
    <label>Campaign Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CampaignMemberStatus__c/fields/HasResponded__c.field-meta.xml
<CustomField>
    <fullName>HasResponded__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should the automatically created campaign member status value be a responded status?</description>
    <inlineHelpText>Should the automatically created campaign member status value be a responded status?</inlineHelpText>
    <label>Responded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMemberStatus__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Should the campaign member status be the default one. Only create one of these per combination of Campaign Type and Record Type.</description>
    <inlineHelpText>Should the campaign member status be the default one. Only create one of these per combination of Campaign Type and Record Type.</inlineHelpText>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMemberStatus__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>The sort order of campaign member status values. Must be a number 3 or greater.</description>
    <inlineHelpText>The sort order of campaign member status values. Must be a number 3 or greater.</inlineHelpText>
    <label>Sort Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/autoCampaignMemberStatusTest.cls
@isTest
private class autoCampaignMemberStatusTest {

    @isTest(seeAllData=true)
    private static void test() {
        CampaignMemberStatusSelector.settings = new List<CampaignMemberStatus__c>{
            new CampaignMemberStatus__c(Campaign_Type__c = 'Conference', Campaign_Member_Status__c='Attended', IsDefault__c=false, SortOrder__c=1, HasResponded__c=true),
            new CampaignMemberStatus__c(Campaign_Type__c = 'Conference', Campaign_Member_Status__c='Declined', IsDefault__c=false, SortOrder__c=2, HasResponded__c=false),
            new CampaignMemberStatus__c(Campaign_Type__c = 'Conference', Campaign_Member_Status__c='No Show', IsDefault__c=false, SortOrder__c=3, HasResponded__c=false),
            new CampaignMemberStatus__c(Campaign_Type__c = 'Conference', Campaign_Member_Status__c='Another', IsDefault__c=false, SortOrder__c=4, HasResponded__c=true)
        };

        Test.startTest();
        insert new Campaign(Name='foo',Type='Conference',isActive=true);
        Database.executeBatch(new CampaignMemberStatusBatch());
        Test.stopTest();

        List<CampaignMemberStatus> statuses = [SELECT Id, CampaignId, Label, HasResponded, IsDefault, SortOrder FROM CampaignMemberStatus];
        system.debug(statuses);
        System.assert(statuses.size()>0, 'New status values should be created: ' + statuses);
    }
}